"""
Research planning schema.

This defines how the planner agent decomposes a user query.
"""

from pydantic import BaseModel, Field
from typing import List


class ResearchPlan(BaseModel):
    """
    Plan generated by the planner agent.
    """

    original_query: str

    route: str = Field(
        ...,
        description="Pipeline route: literature | datascience"
    )

    subtopics: List[str]

    search_queries: List[str]

    max_papers: int


if __name__ == "__main__":
    plan = ResearchPlan(
        original_query="transformer models for medical imaging",
        route="literature",
        subtopics=[
            "transformer architectures",
            "medical imaging applications",
            "benchmark datasets"
        ],
        search_queries=[
            "transformer models medical imaging",
            "vision transformers healthcare",
            "deep learning radiology transformers"
        ],
        max_papers=15
    )

    print(plan.model_dump())